"""chat_session_owner_nullable_and_anonsessionid

Revision ID: 41c0d98c7bad
Revises: baseline_initial_schema
Create Date: 2025-07-20 08:06:21.947618

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '41c0d98c7bad'
down_revision = 'baseline_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatsession', sa.Column('anon_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.alter_column('chatsession', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_chatsession_anon_session_id'), 'chatsession', ['anon_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatsession_anon_session_id'), table_name='chatsession')
    op.alter_column('chatsession', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chatsession', 'anon_session_id')
    # ### end Alembic commands ###
